#include <stdio.h>
#include "solution.h"

// Tests ----------------------------------------------------------------------

// expected answer is 0
void test_1() {
    char word[6] = "aeioqq";
    int k = 1;

    long count = countOfSubstrings(word, k);

    printf("Example 1 - answer: %ld\n", count);
}

// expected answer is 1
void test_2() {
    
    char word[5] = "aeiou";
    int k = 0;

    long count = countOfSubstrings(word, k);

    printf("Example 2 - answer: %ld\n", count);
}

// expected answer is 3
void test_3() {
    char word[14] = "ieaouqqieaouqq";
    int k = 1;

    long count = countOfSubstrings(word, k);

    printf("Example 3 - answer: %ld\n", count);
}

// expected answer is 3
void failed_test_1() {
    char word[8] = "iqeaouqi";
    int k = 2;

    long count = countOfSubstrings(word, k);

    printf("Example 4 - failed test 1 - answer: %ld\n", count);
}

void failed_test_2() {
    char word[10001] = "gocuoabaceaacddducuadccugugiouaguedaboaicoaeadbgobedbacfedfeoieoibbafuaiooeciguucdgiofdgebouaiafauogafbfaoeoeiueucgdocafdbioecieooogicoadbibcdagbbaogoodibeggufdigiucccfgebefgicfidffdgbeebiiciueociobfibgaaoediubaebggicdudicgciuufgfeacefgdccciggbodoabccbgodoiieiiceibobfugagaudboeocobuouffafdfgbueigiiobdoceuccfbuifuggdgagifuauficggiffaeaibagiofcbiucidugiaofiggbefaedfigcibciedauccoiodbbeobiociddaabuieudabgaffdcgggbcaogbfcgoocdeidgceudcafgiecuuiucfgobeciuooueufeuigccdcdcbcfogfiiafociocuuaiebudggfbgabuducedbodbbgdfeggioueuubeioooiefcidebuuobdfocbduuiauieucbbuoiudfcaedceuoieueuubgbaoaioogbefbefduebofeeageageuaaceccogaoegibufiigaudgcaiieddfcdeeiiadaicecdfueuufgoebafeoeibeucfegaiiecdbgfibbieaucccoooiofoadfidfficaufbouadaebubgbbdegbdaucbugabucufudcobuiofocdcdobfiaoodfudideofbfccbaeiougdiiugdueuicfacfcbudafaedgdaafeuiuggdecbabciaoubduccecobgbaooeaiuoucgbefudaduaoucegiaaaocageadfgdfodoiobefibcfgeebifdaeuodeciaieocigcgfbiificdbfeieoucddbfbiucggbiufaddeadabdgcbbfdciabeoobegguieguoaoaouagbfddafdfuuboifbogoddfeodifagdecfcdogacbbbfufcuadudfuofddifuoueagaocccigoiieoafgduedoobcdbdeogiiaobcgouocdbedifcubigigagbaucdbfoaceicfcagdcdgdaeooiaoeouuaiabadcoccdbubbbuiougibioobfgodfcigdbuoouufgcgiefuibbedddacebfgbebfdbuagiodgudfgiugfooibbbuccoogacigaoicobbffobguccfbaddgdibuoogiigieuiaoiudeuafidgcouicffogcauugadiadeaoadbeiaaefobbcefdgddcicicbbiibaaedcdbfdfbooagucadiceiuiafdoguofiubbaubagabbabggoifaaadebiffeudbeebbuooooobouacidobgbfgoicicebcbgdbbecogfuiggdoiaufiaguceoaaccgiucgedoddagbdacbiciabfiaoecbegecffoieugoafufdfeiecaucauegaeoibdgcoegcobffafaacfeubgcgucffcaaugaaufuogdibfbebigubccfuifoeuegcaioafiibeofuubecbudgfaufuudcadfdgedcefoeibefodieaieccgigcobbfdugeebguegduauaeacbffoucdedegbducdbgbuuobdcebicfdifufbudeooocodgdudbaggciubiuudbccogucddcduegbebiaoobouaofceaegfbdbaabafdugoodiaueubooobecggibucdigdbbgobfifoaedegaacicuoibudfiabeiggauucoofiuffcdgbaaigoebfgidfodboaobcieogdogcdgdaaeogffieodedccfifodcdfuediefuggfbdaiecaafgfcidibgacbbfeicgfccbcbuuaeeduuiufbdebcdfucubdegcicgbuiagadofuiuiddaagbigoodgifbifdofoidieedfodbebugiiifuubfogougodaceeggubfafafadibfiafacofbgducuueueefbuadbiagggafiiooeddgboigbcidegaddbgabegfcaoiccbubaccucodfiofdoieigboocfuuocacfidbiodcduguebfcaudocbcgfueoieaceiboadgbduadecbguauadccfcafiaacefofgcuiuegogacgudiuoauibgdadcaooudcoiugeegbeiaofidfcuoaiafedceogobogaidoebbdgbdeogiuabbebodoeeggagufbugedgbddcffoabbaooaucogbfiaffcidobfdbadiffiocobfoaaubicfeieggocugocgucoggiiadgduiadbgdfbccgdfoubfuauuiefbbguaedgifogggafgbbfocicbdffuebafeefuucdgbduaofagouegeuodoigdddaeacdaugbegbeiocbadfoegoaucggfbubcedbeacgoagbooggacecodefafbodbeieufogucfddfiggcegdegofiudigbooaubdogdouudacgaiiiaocfedagdcgcioiufifoeieeecobbcifaafodccaiegebdoiibauecccbbebiciodcaoifobagogfbibicacobfdccbbuooedbbbuaofaedecufugficfaoaobeguddcueuedegfibaiefuaebgdaguiodiguudofaffabogifuddufioofefubfaogggiiugfiegcbcuaucecoieffaobibddfugboauiuaboaeabgdfgifgoaobuuaobdabcoddiouffgoauufuiubbubbgfbifbudeefuugfbaiofiguffffgabiaabffgudgafiiifidbuefaiefffeufocfeaofgebdadgeddoddauodgdccbedbaabfodeobigocacggaicogdudfaebicegaceiaaddicebofoiiogdffcbeuigcdbboifeaceuidfgggcuecbdcgueuueduigogogeooedfabgegdeeeaeugiibebdiebggedfudoafifdoudfeefoeodibdgufgcoibcfgdbebfbdoucbgcafdugbbaegdggaeogdgagbcddbifgguiiacuuidgueoaguigdaoeffbbededubggcccaciogcoaufbodgbiceefacfebbadfefbueogiubfbocobiadefoaffougcdadcgaafiaadiedecdfeacfiibcedofbafuoooeibdaicioufcicbcbeodugbcdbuicbfagudidfceafebeoafugiegobdugieebeagfucbaubbdcocdaeoccebcoficdoufiodgcubciggoieocbcdbegouobuiooaegfieogoddioacfifaioofggdaacfgeaigbuuiidgagcgcoabcffdcboccueaefecddufcediuabugbiaegguiefcocoaagegeoabeffcgbibdccfdbiioaicofubbbgfacbageuebioedbadedifbbeguuouccffigbegefgauccddbceicoibbuuoudcdiaafeugouguacodbdgcdogcdeidgfiucdagaadugbeuebguieocudbauiagifgedfiegicuoufficacabfiaeidegbbbcobacoabggiaaebuicebebbiiebdibafgoeiooaiecffeaegofiodaceidcugoccbiaogofiagfdaauccabofaaegbuebieggifeebeddbgfcoeducoofieouibaageuouiodaaafcuioboigggbciucdoecuucdubegiiocbdcudgocidcdoocgegaucaideaaffgigeefufccfdiouefcifufceuaboueegidaedcfgaciccdfgcoggeufiudaodfoaibedfeaugdfdbaugofdeffudioffcagdbucefieadiecduibcguuugeooceidgueeocaifeeeiadodbgefueoeoogogogbuaeebeiagddouebgbfucbebiooucooefobbcbfueffedoboacaeeadgbefgdcfcdfciabcidduobgbfegggcacdogubgceducfaiedaboufudoeiiaaucoccooouefebgicdudbacoaifeabcbodffufociuuaaufgcafoaiecdoigduocffafaduoogdccubggioeadeafbfaacadgbfcefougccdicffdbddccbebdcdudgauabgfeediaudeccgfofuabuedoebfbgcfocgoeffgcugfiafceicdoogiiafafaegcieduuabfoiuodaffiocccgaufbufcfoacoababfobeagcbaiieedgccidfbegeifieaubgadgbaegfediicbedffedgaabbfcebciogcacgdbbbudcuibagbfedfgbgicoguduooueuebogogedodadfbdfbaedebaaeiiodccdeeaciuaubuigbugdioofofdueifedodoaaoadueidadbdffbgficifgbgfbociffiffifoeeggduaddgffoecoofaeoeacgcodedifadguocueeucgiffccdidaubebaiebodooduedcibuiieuiibiuafuefiiiuaibfobogagoidofdeadbaegoddbouidfcacbbducaeabiiagubbuddiugebegeffobffggeicoefgcigfiggocoeobocibifgfobfudccfdegodieadeaaccogagucaiecgudgeguuodfefdbfcoodofogfdfifgcfcdofiaciagdoedobdobaoieceagoaeoaiigcffuouecgfdcbfdueoufbifgbbgccudbudgoouddfacfgddfeuefoeogibufbaebeccuaefeucfbuebbdfdeouieobefuaofuidgaaffeudoeuududfcebuafgdiecodeaobfaiffeocguifeaeaogigoidbfaccfiedicbdiegffeiidobocbaiudifdgbeguaoacdabaedbidgubouoigfgaccdbguuuuuddoacabdifadbiibcoiidifddeauoofegiooduacbuffieguaddiecgedooafcifgcgfaffbaicfafbbbeegeuacfccgbffbuiaoggdduboocioagcbuegeogccgbbegifugboagguuabbaaocaggcadecidoicbuffeggdfiboueucdacedgdafiicgdefcauoooacobouuduufaogugbadaffcfcfeduoegfdcdebdocbfuiocuoafooggaogefaeecuiadbuocicdbgaccebcofoiiabagioogiiudaiiaffbiicagdgdacbuigafcfugabaoccuogaubcddibuidbaacffiagagebaieedeabceocgueiigobduuboceffbdgogiieiceeueiouideeobocgdfbuodaaugeidgaiifibdigebaffgfoeobaifufauugoidfacabedfcueedducegaueudbbuibbucccegaaecedcidbuiobaefcaoaudiadgggocceifuecbogaeadoigbgagciicccafefuogguafieffcoudgigdegaoododfeucodcicigffbeffaiuboccafeauofaeuabbauibbuiagbfoacfifefooafcddueadfogciaocgggbdfoaogoaaoiggeouoeiodfuoeuboiagooofiicubgfieecgbcaecobuuibaeageicdobfuoiudogbaaubabubbidbbaeggaicfioaaaieodooadubfauuuigafcfdigcgiaeffeaadcbbbffobdacobuicegobefagoeidefoiiofcdabiodideouudgdicfifbduoegccedabfduidfbuiadiuebebguobeeiabodgaagfgiaafogofboaoucuadiaaofffueaioifogaaiafuieiuaiabofdgggaoccbfofeueaafecedbfoeufguoefbeaiieiiuucugibebeeeugiceibcuoifggeocudifbuuafoabdfeoffboicguocbodiffiguifbabfceaddigcagigfgdgiffcdugicfubfiidaeoecdaddoaeiogddibfdfigofeficofcoacacgcoodcfcuugoudiocecdebgeacccbifguoddicdfuufegdbooboggcabdgegbffideiieuudodceidbfgcecafddcoeuffogaeabifegbfuabeoecfofcubooaddeadgcbiddggucboofeacdeagaiobfgifocuuocbeeibaggoedboieogguuogoueodfbfaocdecgbefgddeadfoudoucaucgaufgbcgguauoaiedbauidbcbocguioigufeifaaguiiciboigccuadgficefuiugageiiifubuedgdfadadiacuuciaogugogccgefccgfiebbifuoceuouidugeidgceoufifoifocoocifgecaugaouceufcugdoeuccbobiofufiegddougcbbgiuaaoebfgdegfbooeufaoooiebioigudboicegogubbdguiaaodeidbbodgdgbgdacbuoafiibcaaogoadabaaieaauefoifbugebiuougifdagofuogadcfcoobuoeceogeicoeagecuecbdbdciadcgbcoadiioeicefebiuoubbgbiffaicfgoiigfeobuccdefuiiuafaggbcfoocbebcbacifcgfaoiauababodeuguaefaguuufagccbubaifccbcfgcacagfaaoafefiadagibfddcagbggefaiudaobdfacfcuafdbocogogfcubffdubeibedcouoeofoafebeiucuuggidobfogifuogoiecaiigcaaubocdbgaegdiebgibbiidceiguoofgbbgaaicifbggaceoffogogcoegggecgdocbdgcbfbbduduioeedeieoioofbeuaiedaddgocdacccefffaciiddcefucdgdgbceeebbbuuoogfoubggbcgdfbiiuffuggofdoffudacaogagiediocfdeocgdfaidiioaaaeocabccdfgoiibidffccofcgubauocgbgfofuuccuoeeodcaidbeicgcddoucffagiddigfueooubigcgdeueogdadbuicdebouicicoaidecifgfuiodegaecbgifdcuioiifdduccagofeufggddbfibddbfaoeuofufuiggfdffieccfgfdbbfecbgocoiiocbfibgocufogeuuafudgeeicogaigdcoecuuoeaafofouocfbiooaeeabgcofecoabeooafoiguebaiaogcociaougbaeffccococbcaafiaeidobogebfcubgaeifieaiucugduobeougueccudcecieeoibfddueaofcbbdbibfbadufifdddaecoecbbbigcudgfgioiaefciaediaoabdueicecocogdaofbuodbdabgbiabdffoduieuiaauefoguabeuebcadafcibgggcugdfodfaecigcguaeggibbaaufooucagaegddbuffaduedfubbbucbfugdioucucogefbbbioddeccoeocddigbgocfodaeoeeiufgudboeeuacugbfceaudfefiebocgbgaaauocbbfefdcagdfiiauuecegaedgigoeguaodfbduebbiueeaaadafedggbogaeeggebgguuuuidgaiefuufbofgeabucaodbobofubiucidoocibbgouffogedebioficuoedieudobfciuabdeaofeuuogoiudfbgoaioaigbofeeuegfebcbfiogdbdcgidceudbebgbogbbuueufbiufcfaaoicioduaodcgooggbcoeiacbedufcaiudaiegcgebccgogbgiabeocfgbecocugbuaddiadfeuofifuioideifoeoddicoiuibadfceeufdigaegedfdbciocfodiciadfaodgdggaoaecabcoaoobigbofeudoodeoabdoccbbeodgdiobudfabcdaeeoibbcedoiobcacdicucgefubgdbfgobgaoodufdeabguobgcbeuidcudiuuiaudfofegubcouaabofiaciuecdibccafoaobubifiddbfgbbgofugdeucucifoiuiuaiaebaddboaeeeeeucaiabebboieaedfacafiodedggeieeofeudouafugiooiauccodogufoiebdoaucffeficeoiuideuubeddabdiogoogibggauiibdgugbeuuocaoofiefbgfcuofeucfeedufuaueffcuafaucfiegciaoofibbdddbidddfaofbbbfocgbediuicaddcocdafocduiioaffuuidcbfuefecuuuebcieodugeoiiecbudegcugbogauuougfiiceeaaidegoeidoffaaccduufagfiuiigicbdffufdiafoufcoueafuubdcogubcaiffgcfudgiffgouggguiggcodoegcggffbcbbedfciuedegifuiofebucbdiioieiicbbgfaiueudieiufccobodeuafbuofuocfgeaiuuadeiefdocfbdfuecfeufaauuecbgeaffaibfoacagbeoffucgueoigiegoaiguuebfguucuioiboecbicdeecaguiodocucacoudeoacdabeedugaiuigdaoicoobucaaoigddbuiooiggfgieuieeobcuboabaauaugodeceboaabdugugaoodobcgcagdoogiogoodffugeiuufiiceeacabaobaubidcubgcffdcugabcfaoigcdfcubdoobadiauidcuoebdfaoduaugacefbabbdfubadboudoecoouecaoacaacbbubaecigcogobbaeegauaaaauaeufubbubobigbdguboaooufaeduebeoiffcfeouiuuedggebueufggfggfdibcgacabcecfbdfuiaciidibcoeoebccfdfdfeefbegeabaibubeiuogadggaeieboeacugbcibiuiaeuggdubbgdiebdeaafddebbadedaagcoieeceucbgaggecdfuuaooeccdifuiuedgbuuuagfuaacouifbieecgadgiuubagcgfufifbiudgogadobaoeuoffceiodfbfugcidccceuoegagicbcbbdoofofaciifuuidificaaogudbfbdccfigefogbgugiofbuodebugaaaudaauuoefcbbbicdcufueoueegceeefgfuacacauoebaouieaoeiebfgugacegafoaagoudgcgggdbgccdfidgeioidooadbecgcuugiaiidffdbguuebbbibgufigccaefufiuabdfodfcfcfdgecofedaouuegeebogcgucdbgfaegaabfocgfoeceociodcgeeigabbfgiiubigecgidcdiggggadoaoauuggofgoaudoodbdoifebiicgaecgcdbffigoeieoudebibeebucbdfifddieoaodguucdicbdbeoieoeibiiocdcifcgbduadbbdeueufeigeddcobifafiooofefeddaiacfgueafdgafdbabicbceboccdgfgigcoooufaiddecougfoecodcgiigudoofiguaubuiiueeaguaeedfaubfuobgibibiibobacceoiiugfoueeugcboddgudgbaacgccccf";

    int k = 6351;

    long count = countOfSubstrings(word, k);

    printf("Example 5 - failed test 2 - answer: %ld\n", count);
}

// Main -----------------------------------------------------------------------

int main()
{
    test_1();
    test_2();
    test_3();
    failed_test_1();
    failed_test_2();

    return 0;
}